export const SIGNED_OUT = '@@AUTH/SIGNED_OUT';
export const SIGNED_IN = '@@AUTH/SIGNED_IN';
export const SIGN_IN_CODE_CONFIRMATION = '@@AUTH/SIGN_IN_CODE_CONFIRMATION';
export const SIGN_IN_FAILURE = '@@AUTH/SIGN_IN_FAILURE';
export const VERIFY_USER = '@@AUTH/VERIFY_USER';
export const CODE_VERIFIED = '@@AUTH/CODE_VERIFIED';
export const UNDO_VERIFICATION_CODE = '@@AUTH/UNDO_VERIFICATION_CODE';
export const LOADING = '@@AUTH/LOADING';
